<a href="https://colab.research.google.com/github/prathmeshk71/Hokage/blob/main/Numpy_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
np.version

<module 'numpy.version' from '/usr/local/lib/python3.12/dist-packages/numpy/version.py'>

In [10]:
one_D = np.array([1, 2, 3, 4])
print("it is one-Dimensional array:",one_D)
print("its type:",type(one_D))

it is one-Dimensional array: [1 2 3 4]
its type: <class 'numpy.ndarray'>


In [11]:
twoD_arr = np.array([[1, 2, 3], [4, 5, 6]])
print(twoD_arr)

[[1 2 3]
 [4 5 6]]


In [13]:
threeD_arr = np.array(
    [
        [
            [1, 2, 3], [4, 5, 6]
            ],
        [
            [1, 2, 3], [4, 5, 6]
            ]
        ]
    )
print(threeD_arr)
np.size(threeD_arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


12

In [16]:
records = [
    ("aman", 18, 90),
    ("prakash", 19, 60),
    ("abhijit", 20, 89),
]
print("this Record function:", records)
data = np.array(records, dtype = [("name", "U15"), ("age", np.int32), ("marks", np.float32), ])
data

this Record function: [('aman', 18, 90), ('prakash', 19, 60), ('abhijit', 20, 89)]


array([('aman', 18, 90.), ('prakash', 19, 60.), ('abhijit', 20, 89.)],
      dtype=[('name', '<U15'), ('age', '<i4'), ('marks', '<f4')])

In [18]:
print(data[2])

('abhijit', 20, 89.0)


In [21]:
print(data["marks"])

[90. 60. 89.]
